import Navbar from '@/components/layout/Navbar'
import { createServerSupabaseClient } from '@/lib/supabase-server'
import Link from 'next/link'

const GREEN = 'rgb(34,85,14)'
const INK = 'rgb(26,26,20)'
const MUTED = 'rgb(107,107,88)'

const SECTIONS: { title: string; body: string[] }[] = [
  {
    title: '1. Acceptance of Terms',
    body: [
      'By creating an account or using AceForge ("Service", "we", "us"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service.',
    ],
  },
  {
    title: '2. Description of Service',
    body: [
      'AceForge is an AI-powered study platform. Our features include AI question generation, SAT prep, worksheet creation, and a tutoring marketplace that connects students with independent tutors.',
    ],
  },
  {
    title: '3. User Accounts',
    body: [
      'You must be at least 13 years old to use AceForge. You are responsible for maintaining the security of your account and password, and for all activity that occurs under your account.',
      'You agree to provide accurate, current, and complete information when creating your account and to keep it up to date.',
    ],
  },
  {
    title: '4. Acceptable Use',
    body: [
      'You agree not to use AceForge to cheat on real exams or graded academic work where prohibited by your institution.',
      'You may not harass, threaten, or abuse other users or tutors, abuse the AI generation features, or scrape, crawl, or otherwise extract data from the Service.',
    ],
  },
  {
    title: '5. AI-Generated Content',
    body: [
      'Content generated by AceForge is provided for educational purposes only. AI-generated material is not guaranteed to be accurate, complete, or up to date.',
      'Always verify important information with qualified professionals, teachers, or authoritative sources before relying on it.',
    ],
  },
  {
    title: '6. Tutoring Services',
    body: [
      'AceForge operates a marketplace that connects students with tutors. Tutors are independent contractors and are not employees, agents, or representatives of AceForge.',
      'We do not guarantee the quality, qualifications, or conduct of any tutor and are not liable for the services they provide.',
    ],
  },
  {
    title: '7. Payments & Refunds',
    body: [
      'All payments are processed securely through Stripe. AceForge does not store your card details.',
      'Tutoring sessions are subject to a 48-hour dispute window during which you may raise an issue for review.',
      'Subscription fees are non-refundable except at AceForge\'s sole discretion.',
    ],
  },
  {
    title: '8. Intellectual Property',
    body: [
      'AceForge owns the platform, its software, design, branding, and generated platform content. You retain ownership of the original content you create or upload.',
      'By using the Service you grant us a limited license to process your content solely for the purpose of providing the Service to you.',
    ],
  },
  {
    title: '9. Privacy',
    body: [
      'Our collection and use of your data is described in our Privacy Policy. By using AceForge you consent to those practices.',
    ],
  },
  {
    title: '10. Termination',
    body: [
      'AceForge may suspend or terminate your account at any time, with or without notice, for any violation of these Terms or for conduct we deem harmful to the platform or other users.',
    ],
  },
  {
    title: '11. Limitation of Liability',
    body: [
      'To the maximum extent permitted by law, AceForge is not liable for tutor quality or conduct, the accuracy of AI-generated content, or any indirect, incidental, special, or consequential damages arising from your use of the Service.',
    ],
  },
  {
    title: '12. Governing Law',
    body: [
      'These Terms are governed by and construed in accordance with the laws of the Commonwealth of Virginia, USA, without regard to its conflict of law provisions.',
    ],
  },
  {
    title: '13. Changes to Terms',
    body: [
      'We may update these Terms from time to time. Your continued use of the Service after changes take effect constitutes your acceptance of the revised Terms.',
    ],
  },
  {
    title: '14. Contact',
    body: [
      'Questions about these Terms? Contact us at contactinfo21342@gmail.com.',
    ],
  },
]

export default async function TermsPage() {
  let profile = null
  try {
    const supabase = await createServerSupabaseClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (user) {
      const { data } = await supabase.from('profiles').select('*').eq('id', user.id).single()
      profile = data
    }
  } catch {}

  return (
    <div style={{ minHeight: '100vh', background: 'linear-gradient(135deg, #F4F7EC, #EFF5E3)' }}>
      <Navbar profile={profile} />
      <div className="animate-fade-in" style={{ paddingTop: '5rem', paddingBottom: '4rem' }}>
        <div style={{ maxWidth: '48rem', margin: '0 auto', padding: '2rem' }}>

          <h1 style={{ fontFamily: 'Fraunces, Georgia, serif', fontSize: '2.5rem', fontWeight: 700, color: INK, marginBottom: '0.5rem' }}>
            Terms of Service
          </h1>
          <p style={{ color: MUTED, fontSize: '0.9375rem', marginBottom: '2.5rem' }}>
            Last updated: July 21, 2026
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            {SECTIONS.map((section, i) => (
              <section key={i} style={{
                background: 'white',
                borderRadius: '1rem',
                borderLeft: `3px solid ${GREEN}`,
                padding: '1.5rem 1.75rem',
                boxShadow: '0 1px 3px rgba(34,85,14,0.06)',
              }}>
                <h2 style={{ fontFamily: 'Fraunces, Georgia, serif', fontSize: '1.25rem', fontWeight: 700, color: INK, marginBottom: '0.75rem' }}>
                  {section.title}
                </h2>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                  {section.body.map((para, j) => (
                    <p key={j} style={{ fontSize: '0.9375rem', color: INK, lineHeight: 1.8 }}>{para}</p>
                  ))}
                </div>
              </section>
            ))}
          </div>

          <div style={{ marginTop: '2.5rem', textAlign: 'center' }}>
            <Link href="/privacy" style={{ color: GREEN, fontWeight: 700, textDecoration: 'none', fontSize: '0.9375rem' }}>
              Read our Privacy Policy →
            </Link>
          </div>

        </div>
      </div>
    </div>
  )
}
